//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply_for_job
    {
        public byte apply_for_job_id { get; set; }
        public byte student_id { get; set; }
        public string title_of_apply_for_job { get; set; }
        public string type_of_apply_for_job { get; set; }
        public string time_of_job { get; set; }
        public string wage_of_job { get; set; }
        public string address_of_job { get; set; }
        public string introduce_self { get; set; }
        public Nullable<byte> want_to_recruiter_id { get; set; }
        public System.TimeSpan time_of_apply_job { get; set; }
    }
}
