//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_staff_information
    {
        public byte audit_staff_id { get; set; }
        public string audit_staff_name { get; set; }
        public string audit_staff_login_pass { get; set; }
        public System.TimeSpan audit_staff_regist_time { get; set; }
        public string audit_staff_last_login_time { get; set; }
    }
}
