//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class collect_recruiter
    {
        public byte collect_recruiter_id { get; set; }
        public Nullable<byte> student_id { get; set; }
        public Nullable<byte> recruiter_id { get; set; }
        public System.TimeSpan add_time { get; set; }
    }
}
