//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_information
    {
        public byte job_information_id { get; set; }
        public byte recruiter_id { get; set; }
        public string student_or_recruiter { get; set; }
        public string title_of_job { get; set; }
        public string type_of_job { get; set; }
        public string content_of_job { get; set; }
        public System.DateTime time_of_job { get; set; }
        public string wage_of_job { get; set; }
        public string address_of_job { get; set; }
        public string if_passed { get; set; }
        public int num_of_change { get; set; }
        public Nullable<System.DateTime> time_deal { get; set; }
        public System.TimeSpan publish_time { get; set; }
    }
}
