//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_donot_pass
    {
        public byte job_donot_pass_id { get; set; }
        public byte job_information_id { get; set; }
        public string reason_about_false_pass { get; set; }
        public int num_of_audit { get; set; }
    }
}
