//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_condition
    {
        public byte job_condition_id { get; set; }
        public byte jon_information_id { get; set; }
        public byte student_id { get; set; }
        public byte recruiter_id { get; set; }
        public int finish_condition { get; set; }
        public int student_confirm { get; set; }
        public int recruiter_confirm { get; set; }
    }
}
