//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Y_JobEntities : DbContext
    {
        public Y_JobEntities()
            : base("name=Y_JobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apply_for_job> apply_for_job { get; set; }
        public virtual DbSet<audit_job> audit_job { get; set; }
        public virtual DbSet<audit_recruiter> audit_recruiter { get; set; }
        public virtual DbSet<audit_staff_information> audit_staff_information { get; set; }
        public virtual DbSet<collect_job> collect_job { get; set; }
        public virtual DbSet<collect_recruiter> collect_recruiter { get; set; }
        public virtual DbSet<donot_pass_recruiter> donot_pass_recruiter { get; set; }
        public virtual DbSet<job_condition> job_condition { get; set; }
        public virtual DbSet<job_donot_pass> job_donot_pass { get; set; }
        public virtual DbSet<job_information> job_information { get; set; }
        public virtual DbSet<recruite_condition> recruite_condition { get; set; }
        public virtual DbSet<recruiter_information> recruiter_information { get; set; }
        public virtual DbSet<student_informations> student_informations { get; set; }
        public virtual DbSet<student_is_recruiter> student_is_recruiter { get; set; }
        public virtual DbSet<student_schedule> student_schedule { get; set; }
    }
}
