//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruite_condition
    {
        public byte recruite_condition_id { get; set; }
        public byte job_information { get; set; }
        public byte student_id { get; set; }
        public string if_passed { get; set; }
        public System.TimeSpan time_of_deal { get; set; }
    }
}
