//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruiter_information
    {
        public byte recruiter_id { get; set; }
        public string recruiter_img { get; set; }
        public string recruiter_name { get; set; }
        public string recruiter_type { get; set; }
        public string recruiter_manager_name { get; set; }
        public string recruiter_manager_idcode_type { get; set; }
        public string recruiter_manager_idcode { get; set; }
        public string recruiter_addrss { get; set; }
        public string recruiter_telphone { get; set; }
        public string recruiter_mail { get; set; }
        public int credit_score { get; set; }
        public string menber { get; set; }
        public string recruiter_login_pass { get; set; }
        public System.TimeSpan recruiter_regist_time { get; set; }
        public string if_passed { get; set; }
    }
}
