//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_informations
    {
        public int student_id { get; set; }
        public string student_nick { get; set; }
        public string student_image { get; set; }
        public string student_birthday { get; set; }
        public string student_address { get; set; }
        public string student_telphone { get; set; }
        public string student_qq { get; set; }
        public int time_of_job { get; set; }
        public int credit_score { get; set; }
        public string apply_for_recruit { get; set; }
        public string is_member { get; set; }
        public string student_login_pass { get; set; }
        public System.TimeSpan regist_time { get; set; }
    }
}
